{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "grey-svc-user.fullname" . }}
  labels:
    {{- include "grey-svc-user.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStoreName }}
    kind: {{ .Values.externalSecrets.secretStoreKind }}
  target:
    name: {{ include "grey-svc-user.fullname" . }}-external-secrets
    creationPolicy: {{ .Values.externalSecrets.creationPolicy }}
  data:
    {{- range $key, $remote := .Values.externalSecrets.data }}
    - secretKey: {{ $key }}
      remoteRef:
        key: {{ $remote.key }}
        property: {{ $remote.property }}
        version: {{ $remote.version | quote }}
    {{- end }}
{{- end }}