{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "grey-svc-user.fullname" . }}
  labels:
    {{- include "grey-svc-user.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "grey-svc-user.selectorLabels" . | nindent 6 }}
{{- end }}