replicaCount: 1
ingress:
  enabled: true
  annotations:
    external-dns.alpha.kubernetes.io/hostname: "localstack.lokal.blast.co.id"
    external-dns.alpha.kubernetes.io/ttl: "300"
    external-dns.alpha.kubernetes.io/target: "127.0.0.1"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-grey"
  ingressClassName: "nginx"
  hosts:
    - host: localstack.lokal.blast.co.id
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: localstack-server-tls
      hosts:
        - localstack.lokal.blast.co.id

extraEnvVars:
  - name: SERVICES
    value: "dynamodb,s3"

startServices: "dynamodb,s3"