auth:
  ## @param auth.enabled Enable password authentication
  ##
  enabled: true

  existingSecret: "redis"
  ## @param auth.existingSecretPasswordKey Password key to be retrieved from existing secret
  ## NOTE: ignored unless `auth.existingSecret` parameter is set
  ##
  existingSecretPasswordKey: "REDIS_PASSWORD"

master:
  persistence:
    enabled: false

sentinel:
  persistence:
    enabled: false