auth:
  enabled: true
  existingSecret: "redis"
  existingSecretPasswordKey: "REDIS_PASSWORD"

master:
  persistence:
    enabled: false

replica:
  persistence:
    enabled: false

sentinel:
  persistence:
    enabled: false