apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-grey
spec:
  acme:
    email: imamariefrahmann@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-grey
    solvers:
    - dns01:
        cloudflare:
          email: webmaster@blast.co.id
          apiKeySecretRef:
            name: cloudflare-api-key-secret
            key: api-key
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-grey
spec:
  selfSigned: {}